service: gh-scanner
frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    keepNames: true
    watch:
      pattern:
        - 'src/**/*.ts'
  serverless-offline:
    httpPort: 3000

functions:
  graphql:
    handler: src/handlers/scanner/handler.handler
    events:
      - httpApi:
          path: /graphql
          method: post
